source("setup.R")
source("designBased.R")
# runBYM(tausq=0)
# runBYM(tausq=0, includeUrbanRural=FALSE)
# runBYM(tausq=0, includeCluster=FALSE)
runBYM(tausq=0, includeUrbanRural=FALSE, includeCluster=FALSE)